In [53]:
import numpy as np
import copy

X = np.array([[1,2,3],
              [2,3,4],
              [3,4,5],
              [4,5,6]])
X.shape #4 rows 3 columnns

(4, 3)

In [54]:
w = np.array([10,20,30])

Y = X

for i in range(Y.shape[0]):
    Y[i,:] += w
print(Y)
print(X) #huh how come X and Y are the exact same values?
# This happens because Y is not a new variable. It is merely a pointer to the same varaible 

[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]
[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]


In [55]:
Z = copy.deepcopy(Y)
X += w
print(Z==X)

[[False False False]
 [False False False]
 [False False False]
 [False False False]]


In [56]:
# Broadcasting is a way to perform row wise operations
print(Z)
print(Z + w)
k = np.array([1,0,1])
print(Z*k)
print(Z*(k/2))

[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]
[[21 42 63]
 [22 43 64]
 [23 44 65]
 [24 45 66]]
[[11  0 33]
 [12  0 34]
 [13  0 35]
 [14  0 36]]
[[ 5.5  0.  16.5]
 [ 6.   0.  17. ]
 [ 6.5  0.  17.5]
 [ 7.   0.  18. ]]


In [64]:
#Column-wise broadcasting requires you to define the dimensions of a matrix
print(Z)

#Method 1: Transpose original matrix then transpose back
t = np.array([1,0,1,0])
print((Z.transpose()*t).transpose())

#Method 2: Define dimensions of a matrix

t = np.array([1,0,1,0], ndmin = 2).T # T is also transpose
print(Z*t)

[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]
[[11 22 33]
 [ 0  0  0]
 [13 24 35]
 [ 0  0  0]]
[[11 22 33]
 [ 0  0  0]
 [13 24 35]
 [ 0  0  0]]


In [94]:
#Exercise
# 1) create a list of integers from 0 to 8 (v)
v = np.arange(9)
print(v)
print(' ')

#2) resahpe to a 3x3 matrix (M)
M = v.reshape(3,3)
print(M)
print(' ')

#3) repeat the matrix to a 9x3 (C)
C = np.tile(M,(3,1))
print(C)
print(' ')

#4) broadcast-multiply with initial vector (B)
v = v.reshape(9,1)
print(C*v)

[0 1 2 3 4 5 6 7 8]
 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]
 [ 0  3  6]
 [12 16 20]
 [30 35 40]
 [ 0  6 12]
 [21 28 35]
 [48 56 64]]
