In [18]:
# Suppose you wanted to create a list whose elements are the squares of their indices
import time
import numpy as np

def sqlist(n):
    ct = time.time()
    nlst = np.zeros(n)

    for i in range(n):
        nlst[i] = (i+1)**2

    ft = time.time()
    tt = ft - ct

    return nlst, tt

def sqlist2(n):
    ct = time.time()
    nlst = []

    for i in range(n):
        nlst.append((i+1)**2)

    ft = time.time()
    tt = ft - ct

    return nlst, tt


def sqlist3(n):
    ct = time.time()
    plst = np.array([])

    for i in range(n):
        plst = np.append(plst,(i+1)**2)

    ft = time.time()
    tt = ft - ct

    return plst, tt

def sqlist_fast(n):
    ct = time.time()
    arr = np.square(np.arange(1, n+1))
    return arr, time.time() - ct
    

print(sqlist(11)[0])
lst1 = sqlist2(11)[0]
print(lst1)
print(sqlist3(11)[0])

[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121]
[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]


In [19]:
# There are other ways to initialize variables

print(np.zeros(10))
print(np.full(10,2)) #populates the list with custom values

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[2 2 2 2 2 2 2 2 2 2]


In [20]:
# how to initialize a matrix

r = np.zeros((4,5)) #input must be a tuple not adjacent int values
print(r)
r[0,0] = 1
r[3,4] = 1
print(r)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
# comparing the speed of different functions using the time module. See above

N = 10000

t1 = sqlist(N)[1]
t2 = sqlist2(N)[1]
t3 = sqlist3(N)[1]
t4 = sqlist_fast(N)[1]

print(t1, t2, t3, t4)

#



0.00066375732421875 0.0003955364227294922 0.02003931999206543 2.0742416381835938e-05
