In [2]:
# Python is limited in functionality
# Hence, we import modules or libraries to make certain tasks easier

import numpy as np

In [6]:
lst = [10, 20, 30]
mean = np.mean(lst)
print(mean)

20.0


In [8]:
lstn = np.linspace(1, 9, 5) # returns 5 values between 1 and 9 INCLUSIVE that are equally spaced
print(lstn)

[1. 3. 5. 7. 9.]


In [13]:
nlist = [1,2,3,4,5,6]
nplist = np.array(nlist) # a numpy array is a different data type than python lists
print(type(nlist))
print(type(nplist))
print(nplist) # a numpy list does not have commas separating each element
print(nlist)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5 6]
[1, 2, 3, 4, 5, 6]


In [19]:
#The benefit of using np arrays is that we can call on numpy-specific methods

minvalue = nplist.min()
print(minvalue)
# similarly
minvalue = np.min(nplist)
print(minvalue)
std = nplist.std() # returns standard deviation
print(std)

1
1
1.707825127659933


In [22]:
# Some methods change the variable itself instead 

n= [5,4,3,2,1]
n.sort()
print(n) #variable is permanently changed

[1, 2, 3, 4, 5]


In [29]:
# Using numpy methods could also change the data type

n= n[::-1]
print(n, type(n))
n = np.sort(n)
print(n, type(n)) # data type has changed to np array

[5, 4, 3, 2, 1] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>
